version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dts-db

volumes:
  mongo_data: